---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-c-app-dev
  namespace: development
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: team-c-app-dev
  namespace: team-c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: team-c-app-dev
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: ec685b73-9f21-40e5-8ad5-c13eba4caa09
